services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    tty: true
    stdin_open: true
    environment:
      MODE: DEV
      BINDING: "0.0.0.0"
      POSTGRES_DATABASE: ${POSTGRES_DB:-teammapper-backend-dev}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-teammapper-password}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_USER: ${POSTGRES_USER:-teammapper-user}
      POSTGRES_SSL: ${POSTGRES_SSL:-false}
      POSTGRES_QUERY_TIMEOUT: ${POSTGRES_QUERY_TIMEOUT:-100000}
      POSTGRES_STATEMENT_TIMEOUT: ${POSTGRES_STATEMENT_TIMEOUT:-100000}
      POSTGRES_TEST_DATABASE: ${DOCKER_COMPOSE_APP_ENV_POSTGRES_TEST_DATABASE:-teammapper-backend-test}
      POSTGRES_TEST_HOST: ${DOCKER_COMPOSE_APP_ENV_POSTGRES_HOST:-postgres}
      POSTGRES_TEST_PASSWORD: ${DOCKER_COMPOSE_APP_ENV_POSTGRES_PASSWORD:-teammapper-password}
      POSTGRES_TEST_PORT: ${DOCKER_COMPOSE_APP_ENV_POSTGRES_PORT:-5432}
      POSTGRES_TEST_USER: ${DOCKER_COMPOSE_APP_ENV_POSTGRES_USER:-teammapper-user}
      DELETE_AFTER_DAYS: ${DELETE_AFTER_DAYS:-30}

      TESTING_PLAYWRIGHT_WS_ENDPOINT: "ws://playwright:9323"
      TESTING_PLAYWRIGHT_BASE_URL: "http://app:4200"
    ports:
      - "${APP_FRONTEND_PORT:-4200}:4200"
      - "${APP_BACKEND_PORT:-3000}:3000"
      # karma server
      - 9876:9876
    volumes:
      - .:/home/node/app
      - app_backend_node_modules:/home/node/app/teammapper-backend/node_modules
      - app_frontend_node_modules:/home/node/app/teammapper-frontend/node_modules
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ${POSTGRES_DB:-teammapper-backend-dev}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-teammapper-password}
      POSTGRES_USER: ${POSTGRES_USER:-teammapper-user}
    # Exposing the port is not needed unless you want to access this database instance from the host.
    # Be careful when other postgres docker container are running on the same port
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata

  playwright:
    image: mcr.microsoft.com/playwright:v1.54.2-noble
    container_name: playwright
    depends_on:
      - app
    expose:
      - "9323"
    command: ["npx", "playwright", "run-server", "--port=9323"]

volumes:
  postgres_data:
  app_backend_node_modules:
  app_frontend_node_modules:
