services:
  app:
    build:
      context: ${DEV_BUILD_CONTEXT}
      dockerfile: Dockerfile
      target: development
    tty: true
    stdin_open: true
    volumes:
      - ${DEV_BUILD_CONTEXT}/.claude:/home/node/app/.claude